# Refer to https://github.com/golang/dep/blob/master/docs/Gopkg.toml.md

[metadata.heroku]
  root-package = "github.com/mttrs/reqtrace"
  go-version = "1.12"

[prune]
  go-tests = true
  unused-packages = true
